# Generated by Django 5.0.6 on 2025-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField(blank=True, default='null', null=True)),
                ('opening_balance', models.IntegerField(null=True)),
                ('party_type', models.CharField(max_length=20)),
                ('GST_no', models.CharField(blank=True, max_length=100, null=True)),
                ('PAN_no', models.BigIntegerField(blank=True, null=True)),
                ('billing_add', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_pin', models.IntegerField(blank=True, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.BigIntegerField(blank=True, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
