# Generated by Django 5.0.6 on 2025-03-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('purchase_price', models.IntegerField()),
                ('purchase_gst', models.CharField(max_length=50)),
                ('mrp', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('selling_gst', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=100)),
                ('gst_rate', models.IntegerField()),
                ('low_stock', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
