# Generated by Django 5.0.6 on 2025-03-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
