# Generated by Django 5.0.6 on 2025-03-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_alter_items_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='gst_rate',
            field=models.CharField(max_length=50),
        ),
    ]
