# Generated by Django 5.0.6 on 2025-03-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0007_purchase_bill_purchase_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_bill',
            old_name='tota_qty',
            new_name='total_qty',
        ),
    ]
