# Generated by Django 5.0.6 on 2025-03-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0008_rename_tota_qty_purchase_bill_total_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_bill',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='purchase_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='due_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='paid_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='purchase_items',
        ),
    ]
