# Generated by Django 5.0.6 on 2025-04-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0009_purchase_bill_amount_purchase_bill_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase_bill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchase_bill',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchase_bill',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='purchase_bill',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='due_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='paid_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='total_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_bill',
            name='total_qty',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='purchase_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stockApp.purchase_bill')),
            ],
        ),
    ]
